version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express-app
hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 100
      runas: ec2-user
